update to 1.3.0a2
This also fixes the package to include required components,
as previously we got:

$ python -c "from oslo import messaging"
Traceback (most recent call last):
  File "/usr/lib/.../oslo/messaging/__init__.py", line 18, in <module>
    from .notify import *
    ImportError: No module named notify